### ISSUE TITLE
chinese text ?

### ISSUE THREAD

**Issue by z744364418p** [dongjun-Lee/text-classification-models-tf#2]

**Comment by dongjun-Lee** [comment]
For different language, you should change [clean_str()](https://github.com/dongjun-Lee/text-classification-models-tf/blob/master/data_utils.py#L23-L28), [word_tokenize()](https://github.com/dongjun-Lee/text-classification-models-tf/blob/master/data_utils.py#L67), and [alphabet](https://github.com/dongjun-Lee/text-classification-models-tf/blob/master/data_utils.py#L79)

**Comment by z744364418p** [comment]
tokenize() have been changed "split()",but no work,can you help me? think you

**Comment by z744364418p** [comment]
how to change alphabet for chinese?

**Comment by dongjun-Lee** [comment]
You should remove or change [this line](https://github.com/dongjun-Lee/text-classification-models-tf/blob/master/data_utils.py#L24) in clean_str() because it will remove all chinese characters. You need to define alphabet to use character-level models(char_cnn, vd_cnn). I don't know much about chinese so I'm not sure how to define alphabets in chinese. [koalaGreener/Character-level-Convolutional-Network-for-Text-Classification-Applied-to-Chinese-Corpus](https://github.com/koalaGreener/Character-level-Convolutional-Network-for-Text-Classification-Applied-to-Chinese-Corpus) might help you.
